name: Issue Auto-Labeler

on:
  issues:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Add labels based on title
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const title = issue.title.toLowerCase();
            const labels = [];

            // Phase labels
            if (title.includes('[phase 0]') || title.includes('phase-0')) labels.push('phase-0');
            if (title.includes('[phase 1]') || title.includes('phase-1')) labels.push('phase-1');
            if (title.includes('[phase 2]') || title.includes('phase-2')) labels.push('phase-2');
            if (title.includes('[phase 3]') || title.includes('phase-3')) labels.push('phase-3');
            if (title.includes('[phase 4]') || title.includes('phase-4')) labels.push('phase-4');
            if (title.includes('[phase 5]') || title.includes('phase-5')) labels.push('phase-5');

            // Component labels
            if (title.includes('backend') || title.includes('api')) labels.push('backend');
            if (title.includes('frontend') || title.includes('ui')) labels.push('frontend');
            if (title.includes('docker') || title.includes('container')) labels.push('docker');
            if (title.includes('database') || title.includes('sql')) labels.push('database');
            if (title.includes('launcher')) labels.push('launcher');
            if (title.includes('deploy') || title.includes('production')) labels.push('deployment');

            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: labels
              });
            }
